### ISSUE TITLE
"we found a tech issue in safari. some of the images in one of the homepage carousels aren’t loading. here’s an example, this broken-image frame appears there in every section (whatever that image is doesn’t load on iPhone, either, but it doesn’t give me the broken image frame)"

### ISSUE THREAD

**Issue by stephtngu** [consumer-reports-digital-lab/dark-patterns#91]
![image](https://user-images.githubusercontent.com/60265274/118885840-3d839100-b8c6-11eb-93d8-a79671660d08.png)

**Comment by nathanielfostanperry** [comment]
@stephtngu It's expected behavior for those device images to not get displayed on smaller screens with the lack of real estate. I just pushed an update that should solve the safari issue on desktops though. I wasn't able to replicate the issue however - can you confirm they are loading correctly now?

**Comment by amirad** [comment]
So I reporting it, though it wasn't something I personally found. I did check on my desktop Safari now and the images do show up correctly. The images are working on Safari on my phone as well. All good - thanks for the quick fix!
